from telebot import types

main_markup=types.ReplyKeyboardMarkup(resize_keyboard=True)
item1 = types.KeyboardButton("Акции 💯")
item2 = types.KeyboardButton("Новости 📩")
item3 = types.KeyboardButton("Адреса магазинов 🗺")
item4 = types.KeyboardButton("Социальные сети 📱")
main_markup.row(item1, item2)
main_markup.row(item3, item4)

admin_markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
admin_item1 = types.KeyboardButton("Добавить акцию")
admin_item2 = types.KeyboardButton("Добавить новость")
admin_item3 = types.KeyboardButton("Удалить акцию")
admin_item4 = types.KeyboardButton("Удалить новость")
admin_back = types.KeyboardButton("Назад в бота ↩")
admin_markup.row(admin_item1, admin_item3)
admin_markup.row(admin_item2, admin_item4)
admin_markup.row(admin_back)

city_markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
city1 = types.KeyboardButton("Брестская обл.")
city2 = types.KeyboardButton("Витебская обл.")
city3 = types.KeyboardButton("Гомельская обл.")
city4 = types.KeyboardButton("Гродненская обл.")
city5 = types.KeyboardButton("Минская обл.")
city6 = types.KeyboardButton("Могилевская обл.")
city7 = types.KeyboardButton("Минск")
back = types.KeyboardButton("Назад ↩")
city_markup.row(city1, city2, city3)
city_markup.row(city4, city5, city6)
city_markup.row(city7, back)